"""System theme target: the compositor's colours.

Renders hyprland.lua, a data-only table of hl.config values: window and group
borders, the groupbar and the window shadow. looknfeel.lua applies it over its
vendor colours when the compositor loads its configuration, and exposes
cybexos_system_theme(path), which reload() calls through `hyprctl eval` so a
theme change never needs a full config reload (that would also re-read glass
and display state the shell changes at runtime). A key that user.lua (or
anything else) has set since the theme last applied it is left alone until the
next config reload; see docs/system-theme.md.

Rounding is deliberately absent: it matches Theme.surfaceRadius, a fixed part
of the shell's geometry, and never follows the user's corner setting.
"""
import os
import re
import subprocess

import theme_tokens

NAME = 'hyprland'
FILE = 'hyprland.lua'
EVAL_TIMEOUT = 10

HEADER = """\
-- Generated by CybexOS from the shell's appearance (theme-apply.py). Every
-- theme change replaces this file; set colours of your own in
-- ~/.config/cybexos/hypr/user.lua instead. Data only: looknfeel.lua loads it
-- in an empty environment and uses nothing but the colours below.
"""


def rgb(value):
    return f'rgb({value[1:]})'


def rgba(value, alpha):
    return f'rgba({theme_tokens.rgba(value, alpha)})'


def config(tokens):
    """The theme's hl.config table. looknfeel.lua's vendor values are this
    table for the default dark tokens; a test keeps the two equal."""
    colors = tokens['colors']
    accent, stroke, red = rgb(colors['accent']), rgb(colors['stroke']), rgb(colors['red'])
    # Borders are 0 px in the vendor look, so these only show once user.lua
    # gives windows a border, as the shell's own focus ring would draw it.
    borders = {'active_border': accent, 'inactive_border': stroke}
    group = {
        'border_active': accent, 'border_inactive': stroke,
        'border_locked_active': red, 'border_locked_inactive': stroke,
    }
    groupbar_col = {
        'active': accent, 'inactive': stroke,
        'locked_active': red, 'locked_inactive': stroke,
    }
    # Titles are drawn straight over whatever is behind the groupbar, so they
    # take the mode's ink ladder like the shell's own copy.
    text, muted = rgb(colors['text']), rgb(colors['textMuted'])
    groupbar = {
        'col': groupbar_col,
        'text_color': text, 'text_color_inactive': muted,
        'text_color_locked_active': text, 'text_color_locked_inactive': muted,
    }
    # A dark shadow is the base itself, nearly opaque, as it has always been;
    # on a light desktop that would be a smudge, so there the ink is used,
    # faintly.
    if tokens['mode'] == 'dark':
        shadow = rgba(colors['background'], 0xee / 255)
    else:
        shadow = rgba(colors['text'], 0x30 / 255)
    return {
        'general': {'col': borders},
        'decoration': {'shadow': {'color': shadow}},
        'group': {'col': group, 'groupbar': groupbar},
    }


def lua_table(value, indent):
    pad = '  ' * (indent + 1)
    lines = ['{']
    for key in sorted(value):
        item = value[key]
        rendered = lua_table(item, indent + 1) if isinstance(item, dict) else f'"{item}"'
        lines.append(f'{pad}{key} = {rendered},')
    lines.append('  ' * indent + '}')
    return '\n'.join(lines)


def render(tokens):
    return {FILE: HEADER + 'return ' + lua_table(config(tokens), 0) + '\n'}


def lua_string(value):
    """A Lua string literal that can hold any byte string safely."""
    return '"' + ''.join(ch if re.match(r'[A-Za-z0-9/_.\- ]', ch) else f'\\{b:03d}'
                         for ch in value for b in ch.encode()) + '"'


def first_line(text):
    return (text or '').strip().splitlines()[0] if (text or '').strip() else ''


def reload(tokens, directory):
    # Outside a Hyprland session there is nothing to update: the next
    # compositor start reads the file.
    if not os.environ.get('HYPRLAND_INSTANCE_SIGNATURE'):
        return
    code = f'cybexos_system_theme({lua_string(os.path.join(directory, FILE))})'
    try:
        result = subprocess.run(['hyprctl', 'eval', code], capture_output=True, text=True,
                                timeout=EVAL_TIMEOUT, check=False)
    except FileNotFoundError:
        raise RuntimeError('hyprctl is not installed') from None
    except subprocess.TimeoutExpired:
        raise RuntimeError('Hyprland did not answer') from None
    # hyprctl reports a Lua error as output, sometimes with exit status 0.
    output = (result.stdout or '').strip()
    if result.returncode != 0 or output != 'ok':
        reason = first_line(output) or first_line(result.stderr) or f'exit {result.returncode}'
        raise RuntimeError('Hyprland did not apply the theme: ' + reason)
