"""System theme target: kitty.

Renders kitty.conf, the terminal's colours, into the theme state directory.
The vendor fragment (roles/dotfiles/files/kitty.conf, installed as
~/.config/kitty/cybexos.conf) carries the same keys for the default dark
theme as a fallback and includes this file after them, so these values win
once the shell has exported its appearance. Fonts and opacity stay in the
vendor fragment.

kitty re-reads its configuration, includes and all, on SIGUSR1. Its
auto_reload_config watcher is only given the top-level kitty.conf, so it never
notices this file changing.
"""
import os
import subprocess

import theme_tokens

NAME = 'kitty'

HEADER = (
    '# Generated by theme-apply.py (scripts/theme_kitty.py) from the shell\'s\n'
    '# appearance tokens. Rewritten whenever the appearance changes: put colour\n'
    '# overrides in ~/.config/kitty/kitty.conf after the CYBEXOS MANAGED INCLUDE\n'
    '# block instead.\n'
)

# The GUI instances only, matched on the whole command line: `kitty`, a path
# ending in /kitty, or either with arguments that are not a `+` or `@`
# subcommand (kitty's own is_kitty_gui_cmdline(), which also counts `+open`).
# Python kittens run as `kitty +runpy ...` in overlay windows and die on
# SIGUSR1, whose default action is to terminate, so a plain `pkill -x kitty`
# would close an open Python kitten's overlay. (kitty reads SIGUSR1 through a
# signalfd rather than a handler, so `pkill --require-handler` misses it.)
GUI_PATTERN = r'([^ ]*/)?kitty( \+open)?( [^+@].*)?'
RELOAD_TIMEOUT = 5


def settings(tokens):
    """(key, value) pairs in file order."""
    colors = tokens['colors']
    background, text, accent = colors['background'], colors['text'], colors['accent']
    # accentText already clears 4.5:1 on the shell's panels; the terminal base
    # can differ slightly from them in wallpaper mode.
    accent_text = theme_tokens.ensure_contrast(colors['accentText'], background, 4.5)
    # The shell's own selected fill and the ink it draws on it
    # (Theme.accentContainerFg).
    selection = colors['accentContainer']
    pairs = [
        ('foreground', text),
        ('background', background),
        ('selection_foreground', theme_tokens.foreground_for(selection)),
        ('selection_background', selection),
        ('cursor', accent_text),
        ('cursor_text_color', background),
        ('url_color', accent_text),
        # Filled like the shell's selected chips: accent with its own ink.
        ('active_tab_foreground', colors['onAccent']),
        ('active_tab_background', accent),
        ('inactive_tab_foreground', colors['textMuted']),
        ('inactive_tab_background', colors['surface']),
        ('tab_bar_background', background),
        # A split's border is a thin line on the base, so it needs readable
        # contrast, which a pale accent on a light base does not have.
        ('active_border_color', accent_text),
        ('inactive_border_color', colors['stroke']),
        ('bell_border_color', colors['amber']),
    ]
    # Marks (create_marker) highlight matches; each fill carries its own ink.
    for number, fill in enumerate((accent, colors['amber'], colors['red']), 1):
        pairs.append((f'mark{number}_foreground', theme_tokens.foreground_for(fill)))
        pairs.append((f'mark{number}_background', fill))
    pairs.extend((f'color{index}', value)
                 for index, value in enumerate(theme_tokens.ansi_palette(tokens)))
    return pairs


def render(tokens):
    body = ''.join(f'{key} {value}\n' for key, value in settings(tokens))
    return {'kitty.conf': HEADER + body}


def reload(tokens, directory):
    try:
        result = subprocess.run(
            ['pkill', '--signal', 'USR1', '--uid', str(os.getuid()), '--full', '--exact',
             GUI_PATTERN],
            stdin=subprocess.DEVNULL, capture_output=True, text=True, timeout=RELOAD_TIMEOUT)
    except FileNotFoundError:
        # procps-ng ships pkill on every Fedora install, so a PATH without it
        # is a bare environment (the driver tests run with an empty one), not
        # a desktop. New kitty windows read the file regardless.
        return
    except subprocess.TimeoutExpired:
        raise RuntimeError('pkill did not finish') from None
    # 1 means no kitty is running: nothing to reload.
    if result.returncode not in (0, 1):
        detail = result.stderr.strip().splitlines()
        raise RuntimeError(f'pkill failed with status {result.returncode}'
                           + (f': {detail[-1]}' if detail else ''))
