// The kitty system theme target: scripts/theme_kitty.py and the vendor
// fragment (roles/dotfiles/files/kitty.conf) that falls back to its default
// dark output and includes the generated file.
const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const {
    darkTokens, lightTokens, renderTarget, runDriver, scratch, stubBin,
} = require("./system-theme.cjs");

const repoRoot = path.resolve(__dirname, "../..");
const vendorConf = fs.readFileSync(path.join(repoRoot, "roles/dotfiles/files/kitty.conf"), "utf8");
const INCLUDE = "include ~/.local/state/cybexos/theme/kitty.conf";
const COLOR_LINE = /^([a-z0-9_]+) (#[0-9a-f]{6})$/;
const PKILL_ARGS = "--signal USR1 --uid " + process.getuid()
    + " --full --exact ([^ ]*/)?kitty( \\+open)?( [^+@].*)?";

function settingLines(text) {
    return text.split("\n").filter(line => line && !line.startsWith("#"));
}

function renderKitty(tokens) {
    const files = renderTarget("kitty", tokens);
    assert.deepEqual(Object.keys(files), ["kitty.conf"]);
    return files["kitty.conf"];
}

test("kitty renders every colour as a valid setting for dark and light", () => {
    for (const tokens of [darkTokens(), lightTokens()]) {
        const conf = renderKitty(tokens);
        assert.equal(renderKitty(tokens), conf, "render is deterministic");
        assert.match(conf, /^# Generated by theme-apply\.py \(scripts\/theme_kitty\.py\)/);
        assert.ok(conf.endsWith("\n"));
        const settings = new Map();
        for (const line of settingLines(conf)) {
            const match = line.match(COLOR_LINE);
            assert.ok(match, `${tokens.mode}: not a colour setting: ${line}`);
            assert.ok(!settings.has(match[1]), `${tokens.mode}: ${match[1]} set twice`);
            settings.set(match[1], match[2]);
        }
        for (let i = 0; i < 16; i++)
            assert.ok(settings.has("color" + i), `${tokens.mode}: color${i} missing`);
        for (const key of ["selection_foreground", "selection_background", "cursor",
            "cursor_text_color", "url_color", "active_tab_foreground", "active_tab_background",
            "inactive_tab_foreground", "inactive_tab_background", "active_border_color",
            "inactive_border_color"])
            assert.ok(settings.has(key), `${tokens.mode}: ${key} missing`);
        assert.equal(settings.get("foreground"), tokens.colors.text);
        assert.equal(settings.get("background"), tokens.colors.background);
        assert.equal(settings.get("selection_background"), tokens.colors.accentContainer);
        assert.equal(settings.get("active_tab_background"), tokens.colors.accent);
        assert.equal(settings.get("active_tab_foreground"), tokens.colors.onAccent);
    }
    assert.notEqual(renderKitty(darkTokens()), renderKitty(lightTokens()));
});

test("the vendor fragment's fallback palette is the default dark render", () => {
    const vendor = settingLines(vendorConf).filter(line => COLOR_LINE.test(line));
    assert.deepEqual(vendor, settingLines(renderKitty(darkTokens())));
    assert.doesNotMatch(vendorConf, /Palette matched/);
});

test("the vendor fragment includes the generated file after its fallback", () => {
    const lines = settingLines(vendorConf);
    assert.equal(lines.at(-1), INCLUDE, "the include is the last setting, so it wins");
    assert.equal(lines.filter(line => /^(glob|env|gen)?include /.test(line)).length, 1);
    const tasks = fs.readFileSync(path.join(repoRoot, "roles/dotfiles/tasks/personal.yml"), "utf8");
    assert.match(tasks, /src: kitty\.conf\n\s+dest: "\{\{ primary_home \}\}\/\.config\/kitty\/cybexos\.conf"/);
    assert.match(tasks, /block: "include cybexos\.conf"/);
});

test("kitty is signalled only when its file changed, or on --force", t => {
    const state = scratch(t);
    const stubs = stubBin(t, { pkill: "" });
    const apply = (tokens, args = ["apply"]) => {
        const result = runDriver(state, args, JSON.stringify(tokens) + "\n", { bin: stubs.bin });
        assert.equal(result.status, 0, result.stderr);
        assert.equal(result.report.targets.kitty.error, null);
        return result.report.targets.kitty.changed;
    };
    const pkills = () => stubs.calls().filter(call => call.startsWith("pkill "));

    assert.equal(apply(darkTokens()), true);
    assert.deepEqual(pkills(), ["pkill " + PKILL_ARGS]);
    assert.equal(fs.readFileSync(path.join(state, "kitty.conf"), "utf8"),
        renderKitty(darkTokens()));

    assert.equal(apply(darkTokens()), false);
    assert.equal(pkills().length, 1, "unchanged file: no reload");

    assert.equal(apply(darkTokens(), ["apply", "--force"]), false);
    assert.equal(pkills().length, 2, "--force reloads regardless");

    assert.equal(apply(lightTokens()), true);
    assert.equal(pkills().length, 3);

    const render = runDriver(state, ["render"], "", { bin: stubs.bin });
    assert.equal(render.status, 0, render.stderr);
    assert.equal(pkills().length, 3, "render never reloads");
});

test("no running kitty is not an error; a failing pkill is reported", t => {
    const idle = stubBin(t, { pkill: "exit 1" });
    const quiet = runDriver(scratch(t), ["apply"], JSON.stringify(darkTokens()) + "\n",
        { bin: idle.bin });
    assert.equal(quiet.status, 0, quiet.stderr);
    assert.deepEqual(quiet.report.targets.kitty, { changed: true, error: null });
    assert.equal(idle.calls().length, 1);

    const broken = stubBin(t, { pkill: "echo 'pkill: bad pattern' >&2; exit 2" });
    const state = scratch(t);
    const failed = runDriver(state, ["apply"], JSON.stringify(darkTokens()) + "\n",
        { bin: broken.bin });
    assert.equal(failed.status, 1);
    assert.equal(failed.report.success, false);
    assert.equal(failed.report.targets.kitty.error, "pkill failed with status 2: pkill: bad pattern");
    assert.equal(failed.report.targets.hyprland.error, null, "other targets still ran");
    assert.ok(fs.existsSync(path.join(state, "kitty.conf")), "the file is written before reload");
});
