// Generated by scripts/update-tabler-icons; do not edit.
// Tabler 3.48.0, MIT. See assets/tabler/LICENSE.
var ALIASES = {
    "account_circle": "user-circle",
    "add": "plus",
    "add_location": "map-pin-plus",
    "admin_panel_settings": "shield-lock",
    "alarm": "alarm",
    "api": "api",
    "approval": "rosette-discount-check",
    "apps": "apps",
    "archive": "archive",
    "arrow_back": "arrow-left",
    "arrow_circle_up": "circle-arrow-up",
    "arrow_downward": "arrow-down",
    "arrow_forward": "arrow-right",
    "arrow_upward": "arrow-up",
    "assistant": "sparkles",
    "attach_file": "paperclip",
    "attachment": "paperclip",
    "auto_awesome": "sparkles",
    "badge": "id-badge",
    "balance": "scale",
    "battery_1_bar": "battery-1",
    "battery_2_bar": "battery-1",
    "battery_3_bar": "battery-2",
    "battery_4_bar": "battery-2",
    "battery_5_bar": "battery-3",
    "battery_6_bar": "battery-4",
    "battery_alert": "battery-exclamation",
    "battery_charging_full": "battery-charging",
    "battery_full": "battery-4",
    "battery_saver": "battery-eco",
    "bedtime": "moon",
    "bluetooth": "bluetooth",
    "bluetooth_disabled": "bluetooth-off",
    "bolt": "bolt",
    "calculate": "calculator",
    "call_split": "arrows-split",
    "cancel": "circle-x",
    "cast": "cast",
    "change_circle": "refresh",
    "chat": "message-circle",
    "check": "check",
    "check_box": "checkbox",
    "check_box_outline_blank": "square",
    "check_circle": "circle-check",
    "checklist": "checklist",
    "chevron_left": "chevron-left",
    "chevron_right": "chevron-right",
    "circle": "circle",
    "clarify": "list-details",
    "clear_day": "sun",
    "close": "x",
    "close_fullscreen": "arrows-minimize",
    "cloud": "cloud",
    "cloud_off": "cloud-off",
    "code": "code",
    "coffee": "coffee",
    "commit": "git-commit",
    "compress": "arrows-minimize",
    "computer": "device-desktop",
    "content_copy": "copy",
    "content_paste": "clipboard",
    "dark_mode": "moon",
    "dashboard": "layout-dashboard",
    "data_usage": "chart-donut",
    "delete": "trash",
    "deployed_code_update": "package-export",
    "description": "file-text",
    "devices": "devices",
    "difference": "git-compare",
    "dns": "server",
    "do_not_disturb_on": "circle-minus",
    "document_scanner": "scan",
    "done": "check",
    "done_all": "checks",
    "download": "download",
    "downloading": "download",
    "drag_indicator": "grip-vertical",
    "eco": "leaf",
    "edit": "edit",
    "edit_note": "pencil",
    "edit_square": "edit",
    "enable": "check",
    "error": "alert-circle",
    "event": "calendar",
    "event_available": "calendar-check",
    "event_busy": "calendar-x",
    "expand_less": "chevron-up",
    "expand_more": "chevron-down",
    "extension": "puzzle",
    "files": "files",
    "flag": "flag",
    "foggy": "mist",
    "folder": "folder",
    "folder_open": "folder-open",
    "format_bold": "bold",
    "format_italic": "italic",
    "format_list_bulleted": "list",
    "forum": "messages",
    "function": "math-function",
    "graphic_eq": "wave-sine",
    "group": "users",
    "headphones": "headphones",
    "headset_mic": "headset",
    "help": "help-circle",
    "history": "history",
    "image": "photo",
    "inbox": "inbox",
    "info": "info-circle",
    "input": "login",
    "insights": "chart-line",
    "keep": "pin",
    "key": "key",
    "keyboard": "keyboard",
    "lan": "network",
    "language": "language",
    "light": "sun",
    "light_mode": "sun",
    "link": "link",
    "list": "list",
    "lock": "lock",
    "lock_open": "lock-open",
    "login": "login",
    "logout": "logout",
    "manage_accounts": "user-cog",
    "mark_chat_unread": "message-circle-exclamation",
    "memory": "cpu",
    "menu": "menu",
    "merge": "git-merge",
    "mic": "microphone",
    "mic_off": "microphone-off",
    "monitor": "device-desktop",
    "monitoring": "activity",
    "mood": "mood-smile",
    "more_horiz": "dots",
    "mouse": "mouse",
    "move": "arrows-move",
    "movie": "movie",
    "music_note": "music",
    "nearby": "radar",
    "network_ping": "activity",
    "network_wifi_1_bar": "wifi-1",
    "network_wifi_2_bar": "wifi-2",
    "nightlight": "moon",
    "notes": "notes",
    "notifications": "bell",
    "notifications_active": "bell-ringing",
    "notifications_off": "bell-off",
    "numbers": "hash",
    "opacity": "droplet-half-2",
    "open_in_full": "arrows-maximize",
    "open_in_new": "external-link",
    "output": "logout",
    "overview": "layout-dashboard",
    "palette": "palette",
    "partly_cloudy_day": "cloud",
    "partly_cloudy_night": "cloud",
    "passkey": "key",
    "pause": "player-pause",
    "pending": "dots-circle-horizontal",
    "photo_camera": "camera",
    "pill": "pill",
    "pin": "pin",
    "place": "map-pin",
    "play_arrow": "player-play",
    "power": "plug",
    "power_settings_new": "power",
    "priority_high": "exclamation-mark",
    "progress_activity": "loader-2",
    "psychology": "brain",
    "public": "world",
    "qr_code_2": "qrcode",
    "radio_button_checked": "circle-dot",
    "radio_button_unchecked": "circle",
    "rainy": "cloud-rain",
    "rainy_heavy": "cloud-rain",
    "rainy_light": "cloud-rain",
    "refresh": "refresh",
    "reminder": "alarm",
    "remove": "minus",
    "repeat": "repeat",
    "repeat_one": "repeat-once",
    "reply": "arrow-back-up",
    "restart_alt": "refresh",
    "right_panel_open": "layout-sidebar-right-expand",
    "router": "router",
    "rule": "list-check",
    "save": "device-floppy",
    "scale": "scale",
    "scan": "scan",
    "schedule": "clock",
    "search": "search",
    "search_off": "search-off",
    "security": "shield-lock",
    "select": "selector",
    "send": "send",
    "settings": "settings",
    "shift": "arrow-big-up",
    "shuffle": "arrows-shuffle",
    "signal_disconnected": "antenna-bars-off",
    "skip_next": "player-skip-forward",
    "skip_previous": "player-skip-back",
    "sleep": "zzz",
    "sliders": "adjustments-horizontal",
    "smart_display": "device-tv",
    "smart_toy": "robot",
    "snooze": "alarm-snooze",
    "space_dashboard": "layout-dashboard",
    "speaker": "device-speaker",
    "speed": "gauge",
    "sports_esports": "device-gamepad-2",
    "star": "star",
    "start": "player-play",
    "step": "stairs",
    "sticky_note_2": "note",
    "stop": "player-stop",
    "stop_circle": "player-stop",
    "store": "building-store",
    "stream": "waves-electricity",
    "style": "palette",
    "sunny": "sun",
    "sync": "refresh",
    "sync_disabled": "refresh-off",
    "tag": "tag",
    "terminal": "terminal-2",
    "thunderstorm": "cloud-storm",
    "title": "heading",
    "today": "calendar",
    "tooltip": "message",
    "tune": "adjustments-horizontal",
    "tv": "device-tv",
    "undo": "arrow-back-up",
    "update": "history",
    "upload": "upload",
    "videocam": "video",
    "view_quilt": "layout",
    "visibility": "eye",
    "volume_down": "volume-2",
    "volume_mute": "volume-3",
    "volume_off": "volume-off",
    "volume_up": "volume",
    "wallpaper": "wallpaper",
    "warning": "alert-triangle",
    "watch": "device-watch",
    "weather_snowy": "cloud-snow",
    "web": "browser",
    "web_asset": "browser",
    "widgets": "layout-grid",
    "wifi": "wifi",
    "wifi_find": "wifi",
    "wifi_off": "wifi-off",
    "window": "app-window"
};

var GLYPHS = {
    "activity": {
        "outline": "\ued23"
    },
    "adjustments-horizontal": {
        "outline": "\uec38"
    },
    "alarm": {
        "outline": "\uea04"
    },
    "alarm-snooze": {
        "outline": "\uf632"
    },
    "alert-circle": {
        "outline": "\uea05"
    },
    "alert-triangle": {
        "outline": "\uea06"
    },
    "antenna-bars-off": {
        "outline": "\uf0aa"
    },
    "api": {
        "outline": "\ueffd"
    },
    "app-window": {
        "outline": "\uefe6"
    },
    "apps": {
        "outline": "\uebb6"
    },
    "archive": {
        "outline": "\uea0b"
    },
    "arrow-back-up": {
        "outline": "\ueb77"
    },
    "arrow-big-up": {
        "outline": "\ueddd"
    },
    "arrow-down": {
        "outline": "\uea16"
    },
    "arrow-left": {
        "outline": "\uea19"
    },
    "arrow-right": {
        "outline": "\uea1f"
    },
    "arrow-up": {
        "outline": "\uea25"
    },
    "arrows-maximize": {
        "outline": "\uea28"
    },
    "arrows-minimize": {
        "outline": "\uea29"
    },
    "arrows-move": {
        "outline": "\uf22f"
    },
    "arrows-shuffle": {
        "outline": "\uf000"
    },
    "arrows-split": {
        "outline": "\uedb5"
    },
    "battery-1": {
        "outline": "\uea2f"
    },
    "battery-2": {
        "outline": "\uea30"
    },
    "battery-3": {
        "outline": "\uea31"
    },
    "battery-4": {
        "outline": "\uea32"
    },
    "battery-charging": {
        "outline": "\uea33"
    },
    "battery-eco": {
        "outline": "\uef3c"
    },
    "battery-exclamation": {
        "outline": "\uff1d"
    },
    "bell": {
        "outline": "\uea35"
    },
    "bell-off": {
        "outline": "\uece9"
    },
    "bell-ringing": {
        "outline": "\ued07"
    },
    "bluetooth": {
        "outline": "\uea37"
    },
    "bluetooth-off": {
        "outline": "\ueceb"
    },
    "bold": {
        "outline": "\ueb7b"
    },
    "bolt": {
        "outline": "\uea38"
    },
    "brain": {
        "outline": "\uf59f"
    },
    "browser": {
        "outline": "\uebb7"
    },
    "building-store": {
        "outline": "\uea4e"
    },
    "calculator": {
        "outline": "\ueb80"
    },
    "calendar": {
        "outline": "\uea53"
    },
    "calendar-check": {
        "outline": "\uf824"
    },
    "calendar-x": {
        "outline": "\uf832"
    },
    "camera": {
        "outline": "\uea54"
    },
    "cast": {
        "outline": "\uea56"
    },
    "chart-donut": {
        "outline": "\uea5b"
    },
    "chart-line": {
        "outline": "\uea5c"
    },
    "check": {
        "outline": "\uea5e"
    },
    "checkbox": {
        "outline": "\ueba6"
    },
    "checklist": {
        "outline": "\uf074"
    },
    "checks": {
        "outline": "\uebaa"
    },
    "chevron-down": {
        "outline": "\uea5f"
    },
    "chevron-left": {
        "outline": "\uea60"
    },
    "chevron-right": {
        "outline": "\uea61"
    },
    "chevron-up": {
        "outline": "\uea62"
    },
    "circle": {
        "outline": "\uea6b"
    },
    "circle-arrow-up": {
        "outline": "\uf703"
    },
    "circle-check": {
        "outline": "\uea67"
    },
    "circle-dot": {
        "outline": "\uefb1"
    },
    "circle-minus": {
        "outline": "\uea68"
    },
    "circle-x": {
        "outline": "\uea6a"
    },
    "clipboard": {
        "outline": "\uea6f"
    },
    "clock": {
        "outline": "\uea70"
    },
    "cloud": {
        "outline": "\uea76"
    },
    "cloud-off": {
        "outline": "\ued3e"
    },
    "cloud-rain": {
        "outline": "\uea72"
    },
    "cloud-snow": {
        "outline": "\uea73"
    },
    "cloud-storm": {
        "outline": "\uea74"
    },
    "code": {
        "outline": "\uea77"
    },
    "coffee": {
        "outline": "\uef0e"
    },
    "copy": {
        "outline": "\uea7a"
    },
    "cpu": {
        "outline": "\uef8e"
    },
    "device-desktop": {
        "outline": "\uea89"
    },
    "device-floppy": {
        "outline": "\ueb62"
    },
    "device-gamepad-2": {
        "outline": "\uf1d2"
    },
    "device-speaker": {
        "outline": "\uea8b"
    },
    "device-tv": {
        "outline": "\uea8d"
    },
    "device-watch": {
        "outline": "\uebf9"
    },
    "devices": {
        "outline": "\ueb87"
    },
    "dots": {
        "outline": "\uea95"
    },
    "dots-circle-horizontal": {
        "outline": "\uea91"
    },
    "download": {
        "outline": "\uea96"
    },
    "droplet-half-2": {
        "outline": "\uee81"
    },
    "edit": {
        "outline": "\uea98"
    },
    "exclamation-mark": {
        "outline": "\uefb4"
    },
    "external-link": {
        "outline": "\uea99"
    },
    "eye": {
        "outline": "\uea9a"
    },
    "file-text": {
        "outline": "\ueaa2"
    },
    "files": {
        "outline": "\uedef"
    },
    "flag": {
        "outline": "\ueaa6"
    },
    "folder": {
        "outline": "\ueaad"
    },
    "folder-open": {
        "outline": "\ufaf7"
    },
    "gauge": {
        "outline": "\ueab1"
    },
    "git-commit": {
        "outline": "\ueab3"
    },
    "git-compare": {
        "outline": "\ueab4"
    },
    "git-merge": {
        "outline": "\ueab5"
    },
    "grip-vertical": {
        "outline": "\uec01"
    },
    "hash": {
        "outline": "\ueabc"
    },
    "heading": {
        "outline": "\uee9b"
    },
    "headphones": {
        "outline": "\ueabd"
    },
    "headset": {
        "outline": "\ueb90"
    },
    "help-circle": {
        "outline": "\uf91d"
    },
    "history": {
        "outline": "\uebea"
    },
    "id-badge": {
        "outline": "\ueff7"
    },
    "inbox": {
        "outline": "\ueac4"
    },
    "info-circle": {
        "outline": "\ueac5"
    },
    "italic": {
        "outline": "\ueb93"
    },
    "key": {
        "outline": "\ueac7"
    },
    "keyboard": {
        "outline": "\uebd6"
    },
    "language": {
        "outline": "\uebbe"
    },
    "layout": {
        "outline": "\ueadb"
    },
    "layout-dashboard": {
        "outline": "\uf02c"
    },
    "layout-grid": {
        "outline": "\uedba"
    },
    "layout-sidebar-right-expand": {
        "outline": "\uf007"
    },
    "leaf": {
        "outline": "\ued4f"
    },
    "link": {
        "outline": "\ueade"
    },
    "list": {
        "outline": "\ueb6b"
    },
    "list-check": {
        "outline": "\ueb6a"
    },
    "list-details": {
        "outline": "\uef40"
    },
    "loader-2": {
        "outline": "\uf226"
    },
    "lock": {
        "outline": "\ueae2"
    },
    "lock-open": {
        "outline": "\ueae1"
    },
    "login": {
        "outline": "\ueba7"
    },
    "logout": {
        "outline": "\ueba8"
    },
    "map-pin": {
        "outline": "\ueae8"
    },
    "map-pin-plus": {
        "outline": "\uf956"
    },
    "math-function": {
        "outline": "\ueeb2"
    },
    "menu": {
        "outline": "\ueaeb"
    },
    "message": {
        "outline": "\ueaef"
    },
    "message-circle": {
        "outline": "\ueaed"
    },
    "message-circle-exclamation": {
        "outline": "\uf977"
    },
    "messages": {
        "outline": "\ueb6c"
    },
    "microphone": {
        "outline": "\ueaf0"
    },
    "microphone-off": {
        "outline": "\ued16"
    },
    "minus": {
        "outline": "\ueaf2"
    },
    "mist": {
        "outline": "\uec30"
    },
    "mood-smile": {
        "outline": "\ueaf7"
    },
    "moon": {
        "outline": "\ueaf8"
    },
    "mouse": {
        "outline": "\ueaf9"
    },
    "movie": {
        "outline": "\ueafa"
    },
    "music": {
        "outline": "\ueafc"
    },
    "network": {
        "outline": "\uf09f"
    },
    "note": {
        "outline": "\ueb6d"
    },
    "notes": {
        "outline": "\ueb6e"
    },
    "package-export": {
        "outline": "\uf07a"
    },
    "palette": {
        "outline": "\ueb01"
    },
    "paperclip": {
        "outline": "\ueb02"
    },
    "pencil": {
        "outline": "\ueb04"
    },
    "photo": {
        "outline": "\ueb0a"
    },
    "pill": {
        "outline": "\uec44"
    },
    "pin": {
        "outline": "\uec9c"
    },
    "player-pause": {
        "outline": "\ued45"
    },
    "player-play": {
        "outline": "\ued46"
    },
    "player-skip-back": {
        "outline": "\ued48"
    },
    "player-skip-forward": {
        "outline": "\ued49"
    },
    "player-stop": {
        "outline": "\ued4a"
    },
    "plug": {
        "outline": "\uebd9"
    },
    "plus": {
        "outline": "\ueb0b"
    },
    "power": {
        "outline": "\ueb0d"
    },
    "puzzle": {
        "outline": "\ueb10"
    },
    "qrcode": {
        "outline": "\ueb11"
    },
    "radar": {
        "outline": "\uf017"
    },
    "refresh": {
        "outline": "\ueb13"
    },
    "refresh-off": {
        "outline": "\uf18d"
    },
    "repeat": {
        "outline": "\ueb72"
    },
    "repeat-once": {
        "outline": "\ueb71"
    },
    "robot": {
        "outline": "\uf00b"
    },
    "rosette-discount-check": {
        "outline": "\uf1f8"
    },
    "router": {
        "outline": "\ueb18"
    },
    "scale": {
        "outline": "\uebc2"
    },
    "scan": {
        "outline": "\uebc8"
    },
    "search": {
        "outline": "\ueb1c"
    },
    "search-off": {
        "outline": "\uf19c"
    },
    "selector": {
        "outline": "\ueb1d"
    },
    "send": {
        "outline": "\ueb1e"
    },
    "server": {
        "outline": "\ueb1f"
    },
    "settings": {
        "outline": "\ueb20"
    },
    "shield-lock": {
        "outline": "\ued58"
    },
    "sparkles": {
        "outline": "\uf6d7"
    },
    "square": {
        "outline": "\ueb2c"
    },
    "stairs": {
        "outline": "\ueca6"
    },
    "star": {
        "outline": "\ueb2e"
    },
    "sun": {
        "outline": "\ueb30"
    },
    "tag": {
        "outline": "\ud800\udc96"
    },
    "terminal-2": {
        "outline": "\uebef"
    },
    "trash": {
        "outline": "\ueb41"
    },
    "upload": {
        "outline": "\ueb47"
    },
    "user-circle": {
        "outline": "\uef68"
    },
    "user-cog": {
        "outline": "\uf9d4"
    },
    "users": {
        "outline": "\uebf2"
    },
    "video": {
        "outline": "\ued22"
    },
    "volume": {
        "outline": "\ueb51"
    },
    "volume-2": {
        "outline": "\ueb4f"
    },
    "volume-3": {
        "outline": "\ueb50"
    },
    "volume-off": {
        "outline": "\uf1c3"
    },
    "wallpaper": {
        "outline": "\uef56"
    },
    "wave-sine": {
        "outline": "\uecd4"
    },
    "waves-electricity": {
        "outline": "\ufcc5"
    },
    "wifi": {
        "outline": "\ueb52"
    },
    "wifi-1": {
        "outline": "\ueba4"
    },
    "wifi-2": {
        "outline": "\ueba5"
    },
    "wifi-off": {
        "outline": "\uecfa"
    },
    "world": {
        "outline": "\ueb54"
    },
    "x": {
        "outline": "\ueb55"
    },
    "zzz": {
        "outline": "\uf228"
    }
};

// Existing semantic names remain valid for built-ins and plugins.
function canonical(name) {
    var key = String(name || "");
    return Object.prototype.hasOwnProperty.call(ALIASES, key) ? ALIASES[key] : key;
}

function has(name) {
    return Object.prototype.hasOwnProperty.call(GLYPHS, canonical(name));
}

function resolve(name) {
    if (!name) return { outline: "" };
    return has(name) ? GLYPHS[canonical(name)] : GLYPHS["help-circle"];
}

if (typeof module !== "undefined")
    module.exports = { ALIASES: ALIASES, GLYPHS: GLYPHS,
        canonical: canonical, has: has, resolve: resolve };
